### ISSUE TITLE
Spring concurrent testing using MTC in spring project

### ISSUE THREAD

**Issue by MattiaRiola** [MattiaRiola/concurrency-testing#4]
# TODOs

- [x] course student exams spring project
- [x] Test single thread repository
- [x] Test multi thread repository
- [x] Test single thread service
- [ ] Test multi thread service 

## Problems

MTC does not cover automatically all the interleaving of the threads, interleaving must be introduced manually with specific test cases using mtc's apis (see concurrencyTest to see a practical example)
